# docker-compose.yml

version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${HEALTH_CHECK_PORT}:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HEALTH_CHECK_PORT
      - HEALTH_CHECK_LOG_INTERVAL
      - HEALTH_CHECK_INTERVAL
      - CRON_SCHEDULE
      - LOG_LEVEL
      - LOG_MAX_SIZE
      - LOG_MAX_FILES
      - ALERT_TYPE
      - COUCHBASE_HOST
      - COUCHBASE_USERNAME
      - COUCHBASE_PASSWORD
      - SERVICE_CHECK_INTERVAL
      - DCP_BACKLOG_THRESHOLD
      - SERVICE_NAME
      - SERVICE_VERSION
      - DEPLOYMENT_ENVIRONMENT
      - TRACES_ENDPOINT
      - METRICS_ENDPOINT
      - LOGS_ENDPOINT
      - METRIC_READER_INTERVAL
      - CONSOLE_METRIC_READER_INTERVAL
      - SLACK_WEBHOOK_URL
      - TEAMS_WEBHOOK_URL
